version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: webservice-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=45.9.62.111 #optional
      - SERVERPORT=51820 #optional
      - PEERS=3 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0, 192.168.0.0/24 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./vpn_config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
      - 54000:54000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
  backend:
    build: ./backend
    container_name: webservice-backend
    environment:
      - PORT=54000
    depends_on:
      - wireguard
    network_mode: container:webservice-wireguard
  frontend:
    build: ./frontend
    container_name: webservice-frontend
    ports:
      - 3000:3000
