version: "2.1"
services:
  wireguard:
    build:
      context: ./wireguard
    container_name: webservice-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=secured-smart-home.de #optional, to be updated
      - SERVERPORT=51820 #optional
      - PEERS=3 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS=25 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./vpn_config:/config
      - /lib/modules:/lib/modules #optional
      - ./logs:/logs
    ports:
      - 51820:51820/udp
      - 54001:54001 # webservice-backend
      - 54000:3000 # webservice-frontend
      # - 54002:27017/tcp # webservice-database
      - 3000:3002 # Wireshark: Access via http
      - 3001:3003 # Wireshark: Access via https
      - 54003:54003 # Gotify: ssl port
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_AXIOS_URL=https://secured-smart-home.de:54001 # set to http:// if HTTPS=false
    container_name: webservice-frontend
    environment:
      - HTTPS=true
      - SSL_KEY_FILE=./../ssl_certificate/key.pem
      - SSL_CRT_FILE=./../ssl_certificate/crt.pem
      - REACT_APP_AXIOS_URL=https://secured-smart-home.de:54001 # set to http:// if HTTPS=false
    volumes:
      - ./ssl_certificate:/ssl_certificate
      - ./logs:/logs
    depends_on:
      - wireguard
    network_mode: container:webservice-wireguard
  backend:
    build: ./backend
    container_name: webservice-backend
    environment:
      - HTTPS=true
      - PORT=54001
      - DB_HOST=127.0.0.1
      - DB_PORT=27017
      - DB_NAME=secured_smart_home
      - DB_USERNAME=admin
      - DB_USERPASSWORD=HighlyConfidentialPassword
      - AXIOS_URL=https://10.13.13.2:8087 # if using a VPN connection, the adress of the iobroker peer
      - WEBSOCKET_URL=https://10.13.13.2:8084 # if using a VPN connection, the adress of the iobroker peer
      - AUTH_SECRET_ACCESS=secured-smart-home-access
      - AUTH_SECRET_REFRESH=secured-smart-home-refresh
      - CORS_ORIGIN=https://secured-smart-home.de:54000 # the frontend address # set to http:// if HTTPS=false
      - LOGGING_LVL=DEBUG
      - GOTIFY_URL=https://secured-smart-home.de:54002 # the gotify address
      - GOTIFY_TOKEN=A9LkayEzlGkBMaj # the gotify token
    volumes:
      - ./ssl_certificate:/ssl_certificate
      - ./logs:/logs
    depends_on:
      - wireguard
      - database
    network_mode: container:webservice-wireguard
  database:
    image: mongo:4.4.19
    container_name: webservice-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: HighlyConfidentialPassword
    volumes:
      - ./database:/data/db
    depends_on:
      - wireguard
    network_mode: container:webservice-wireguard
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: webservice-wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    depends_on:
      - wireguard
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=abc
      - PASSWORD=abc
      - CUSTOM_PORT=3002
      - CUSTOM_HTTPS_PORT=3003
    volumes:
      - /path/to/config:/config
      - ./logs:/logs
    restart: unless-stopped
  inotify:
    build:
      context: ./inotify
    container_name: webservice-inotify
    environment:
      - VOLUMES=/data/db
      #- WATCH_DIFFERENCES=
    volumes:
      - ./database:/data/db
      - ./logs:/logs
    restart: unless-stopped
  tshark:
    build:
      context: ./tshark
    container_name: tshark
    depends_on:
      - wireguard
    environment:
      - TSHARK_DURATION=3600
      - TSHARK_FILES=24
      - TSHARK_ETH0_FILTER=(port 51820) or (port 54000) or (port 54001)
    network_mode: service:wireguard
    volumes:
      - ./logs:/logs
    restart: unless-stopped
  gotify:
    image: gotify/server
    container_name: webservice-gotify
    environment:
      - TZ="Europe/Berlin"
      - GOTIFY_SERVER_PORT=53003
      - GOTIFY_SERVER_KEEPALIVEPERIODSECONDS=0
      - GOTIFY_SERVER_LISTENADDR=
      - GOTIFY_SERVER_SSL_ENABLED=true
      - GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=true
      - GOTIFY_SERVER_SSL_LISTENADDR=
      - GOTIFY_SERVER_SSL_PORT=54003
      - GOTIFY_SERVER_SSL_CERTFILE=/ssl_certificate/crt.pem
      - GOTIFY_SERVER_SSL_CERTKEY=/ssl_certificate/key.pem
      - GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=false
      - GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS=false
      - GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE=certs
      # GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS=- mydomain.tld\n- myotherdomain.tld
      # GOTIFY_SERVER_RESPONSEHEADERS="X-Custom-Header:\"custom value\""
      # GOTIFY_SERVER_CORS_ALLOWORIGINS="- \".+.example.com\"\n- \"otherdomain.com\""
      # GOTIFY_SERVER_CORS_ALLOWMETHODS="- \"GET\"\n- \"POST\""
      # GOTIFY_SERVER_CORS_ALLOWHEADERS="- \"Authorization\"\n- \"content-type\""
      # GOTIFY_SERVER_STREAM_ALLOWEDORIGINS="- \".+.example.com\"\n- \"otherdomain.com\""
      - GOTIFY_SERVER_STREAM_PINGPERIODSECONDS=45
      - GOTIFY_DATABASE_DIALECT=sqlite3
      - GOTIFY_DATABASE_CONNECTION=data/gotify.db
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=admin
      - GOTIFY_PASSSTRENGTH=10
      - GOTIFY_UPLOADEDIMAGESDIR=data/images
      - GOTIFY_PLUGINSDIR=data/plugins
      - GOTIFY_REGISTRATION=false
    network_mode: service:wireguard
    volumes:
      - ./gotify/data:/app/data
      - ./ssl_certificate:/ssl_certificate
    restart: unless-stopped