{
 "title": "Logging",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Event Timeline",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (count_over_time({job=\"inotify\"} [$__interval]))"
    },
    {
     "expr": "sum by(job) (count_over_time({job=\"wireguard\"} [$__interval]))"
    },
    {
     "expr": "sum by(job) (count_over_time({job=\"backend\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Inotify",
   "type": "logs",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"inotify\"} | pattern `'<time>' | '<date>' | Directory: '<directory>' | File: '<file>' | Action: '<action>'`"
    }
   ]
  },
  {
   "title": "Wireguard",
   "type": "logs",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"wireguard\"}"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "logs",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"backend\"}"
    }
   ]
  }
 ]
}