# config file version
apiVersion: 1

# list of datasources to insert/update depending
# on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <string> url
  url: http://prometheus:9090

- name: Loki
  # <string, required> datasource type. Required
  type: loki
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <string> url
  url: http://loki:3100